# General settings
title: Mechanics at Civil Engineering
author:  Tom van Woudenberg
email: T.R.vanWoudenberg@tudelft.nl
logo: images/TUDelft_logo_rgb.png

repository:
  url: https://gitlab.tudelft.nl/interactivetextbooks-citg/mechanics
  branch: main
  path_to_book: book

html:
  extra_footer: <img src="https://i.creativecommons.org/l/by/4.0/88x31.png" width="88px">

# Execute notebooks when building
execute:
  execute_notebooks: 'off'

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false
    use_thebe_lite: true
    exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]

bibtex_bibfiles:
  - references.bib